<?php
$data = [
    'service'  => 'Twitter',
    'endpoints' => [
        [
            'section' => 'Help',
            'requests' => [
                [
                    'uri'      => '/twitter/help/getConfiguration',
                    'method'   => 'GET',
                    'endpoint' => 'help/configuration',
                    'libCall'  => 'PHPoAuthImpl\Service\Twitter\Help::getConfiguration()',
                    'docs'     => 'https://dev.twitter.com/docs/api/1.1/get/help/configuration',
                ],
                [
                    'uri'      => '/twitter/help/getLanguages',
                    'method'   => 'GET',
                    'endpoint' => 'help/languages',
                    'libCall'  => 'PHPoAuthImpl\Service\Twitter\Help::getLanguages()',
                    'docs'     => 'https://dev.twitter.com/docs/api/1.1/get/help/languages',
                ],
                [
                    'uri'      => '/twitter/help/getPrivacy',
                    'method'   => 'GET',
                    'endpoint' => 'help/privacy',
                    'libCall'  => 'PHPoAuthImpl\Service\Twitter\Help::getPrivacy()',
                    'docs'     => 'https://dev.twitter.com/docs/api/1.1/get/help/privacy',
                ],
                [
                    'uri'      => '/twitter/help/getTos',
                    'method'   => 'GET',
                    'endpoint' => 'help/tos',
                    'libCall'  => 'PHPoAuthImpl\Service\Twitter\Help::getTos()',
                    'docs'     => 'https://dev.twitter.com/docs/api/1.1/get/help/tos',
                ],
                [
                    'uri'      => '/twitter/help/getRateLimitStatus',
                    'method'   => 'GET',
                    'endpoint' => 'help/rate_limit_status',
                    'libCall'  => 'PHPoAuthImpl\Service\Twitter\Help::getRateLimitStatus([<span class="type">array</span> $resources <span class="default">= array()</span>])',
                    'docs'     => 'https://dev.twitter.com/docs/api/1.1/get/help/rate_limit_status',
                ],
            ],
        ],
    ],
];

require __DIR__ . '/../endpoints.phtml';
