<!DOCTYPE html>
<html>
    <head>
        <title>Demo for the PHPoAuthImplementations library</title>
        <meta charset="utf-8">
        <script>'article aside footer header main nav section time'.replace(/\w+/g,function(n){document.createElement(n)})</script>
        <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:700italic,400' rel='stylesheet' type='text/css'>
        <link href="/style/style.css" rel="stylesheet" type="text/css" media="screen"></style>
    </head>
    <body>
        <div id="container">
            <header>
                <h1><a href="/">PHPoAuthLib Demo</a></h1>
            </header>
            <div id="content">
                <?php echo $content; ?>
            </div>
            <footer>
                <ul>
                    <li>Powered by the <a href="https://github.com/DaveRandom/json-prettifier" target="_blank">JSON Prettifier</a>, <a href="https://github.com/Lusitanian/PHPoAuthLib" target="_blank">PHPoAuthLib</a> and <a href="https://github.com/PeeHaa/PHPoAuthImpl" target="_blank">PHPoAuthImpl</a> libaries</li>
                </ul>
            </footer>
        </div>
        <script src="/js/main.js"></script>
        <?php if (isset($analytics) && $analytics['code'] !== null) { ?>
            <script>
              (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
              (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
              m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
              })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

              ga('create', '<?php echo $analytics['code']; ?>', '<?php echo $analytics['domain']; ?>');
              ga('send', 'pageview');

            </script>
        <?php } ?>
    </body>
</html>
