<!DOCTYPE html>
<html>
    <head>
        <title>Demo for the PHPoAuthImplementations library</title>
        <meta charset="utf-8">
        <script>'article aside footer header main nav section time'.replace(/\w+/g,function(n){document.createElement(n)})</script>
        <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:700italic,400' rel='stylesheet' type='text/css'>
        <link href="/style/style.css" rel="stylesheet" type="text/css" media="screen"></style>
    </head>
    <body>
        <div id="container">
            <header>
                <h1><a href="/">PHPoAuthLib Demo</a></h1>
            </header>
            <div id="content">
                <?php echo $content; ?>
            </div>
            <footer>
                <ul>
                    <li>Powered by the <a href="https://github.com/DaveRandom/json-prettifier" target="_blank">JSON Prettifier</a>, <a href="https://github.com/Lusitanian/PHPoAuthLib" target="_blank">PHPoAuthLib</a> and <a href="https://github.com/PeeHaa/PHPoAuthImpl" target="_blank">PHPoAuthImpl</a> libaries</li>
                </ul>
            </footer>
        </div>
        <script src="/js/main.js"></script>
    </body>
</html>
